# Generated by Django 4.2 on 2023-05-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_blog_files"),
    ]

    operations = [
        migrations.RemoveField(model_name="file", name="foreign_key",),
        migrations.AddField(
            model_name="file",
            name="blog",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_file",
                to="core.blog",
            ),
            preserve_default=False,
        ),
    ]
